[package]
name = "qqmusic-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
md5 = "0.7.0"
rand = "0.8.5"
reqwest = "0.11.18"
thiserror = "1.0.44"
tokio = { version = "1.30.0", features = ["full"] }
